{% set name = "synphot" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5d09a56d301b3ae78244cd22c407509b78fab84addfe80e6f662bebd99c95940

build:
  detect_binary_files_with_prefix: false
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools_scm
    - extension-helpers
    - numpy 1.16.*  # [py==36]
    - numpy 1.16.*  # [py==37]
    - numpy 1.17.*  # [py>=38]
  run:
    - astropy
    - numpy 1.16.*  # [py==36]
    - numpy 1.16.*  # [py==37]
    - numpy 1.17.*  # [py>=38]
    - python
    - scipy

test:
  imports:
    - synphot

about:
  home: https://www.github.com/spacetelescope/synphot_refactor
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Synthetic photometry
  description: |
    This is a replacement for IRAF STSDAS SYNPHOT and ASTROLIB PYSYNPHOT,
    utilizing Astropy and covering the non-instrument specific portions of
    the old packages.
  doc_url: https://synphot.readthedocs.io/en/latest/
  dev_url: https://www.github.com/spacetelescope/synphot_refactor

extra:
  recipe-maintainers:
    - mwcraig
    - pllim
