{% set name = "synphot" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eb7c63c450c6cc5ef8db0c9dd41cd95a4647c95f4769acf1d30bb89061a8358b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<310]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
    - numpy
    - extension-helpers
  run:
    - python
    - scipy
    - astropy-base

test:
  imports:
    - synphot

about:
  home: https://www.github.com/spacetelescope/synphot_refactor
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Synthetic photometry
  description: |
    This is a replacement for IRAF STSDAS SYNPHOT and ASTROLIB PYSYNPHOT,
    utilizing Astropy and covering the non-instrument specific portions of
    the old packages.
  doc_url: https://synphot.readthedocs.io
  dev_url: https://www.github.com/spacetelescope/synphot_refactor

extra:
  recipe-maintainers:
    - mwcraig
    - pllim
