travis:
  secure:
    BINSTAR_TOKEN: rH5uLeFy5yLbvOXosUXT/HKW1kiw5WWRPFYlSGJ5BC6/A3wCwwR7CkvoCD3NSgU/KzgHljFjDdgLohSvg2naJ42M5zlzOhm9bPqQoGvyimuW8+PXYRJelxJpbBWIKPDv8sy8v9nH2cIrfC/0XK+ER6xi55EF88TNa1PsIb+BKk+Ij3SQ6bmMj0grpdMoSI1tugnHZ0Gb6Ez5ib2NO7JBmwLZHCe1PkY9eAZWVVJAhNQB93yO1p6F00Cv9IKmEo8bDARuTNEFKFmXYTeVU1cMG9wZLBSxq6TcDqQ8bVxuRsPraWd1qbQe7nhrEEmsEluSHsdri1K8+Igqg5LATQ45Cj3vklcgkBE2l+nG+U/V0LNNNOYyKXINIX1nsnj7KFN/1PFfNW0tciPDjcFfXeBxQ0BhQr8kOCewwFXo4e2XPecI6XJeG883qbPHVRzYKQzjXDqfglrQrXUpyX7EKvls7O1kism9QQ0bvdMUJOFjbcl6bn65DRN9J1zM32KGdU4U1gNJeymnnou6FC68xMqR6aneRNTO48ATruTtexNzZXQmzQY1tpNy+c6n42obsYZc1kYCHFnNoDnKVLrYQ2c31fFoJJpFUxarYKvP4Ymko2oJtJgl3ftym+uoaUsXVg9kX+BhOkK+HLjAjXCvj4sOYa+SEoBzqh+/9QkGn31pRfg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
